### PR TITLE
Implement support for macOS

### PR DESCRIPTION
**Pull request by anton-matosov**
Install Rojo in macOS using cargo

Update libs to latest versions to fix ts build errors and security audit warnings

### CODE REVIEW

**Comment by anton-matosov** [comment]
You are welcome! Yes, I have tested it extensively on Mac. However I didn't run regression test on Windows yet because I have retired my Windows machine )) and need more time recovering it and setting up everything there. It will be great if you can help re-testing the Windows part

**Comment by evaera** [comment]
Yeah, no worries, will test on Windows.

**Comment by evaera** [comment]
Tested on Windows and still seems to work great. thanks

**Comment by evaera** [comment]
Hey @anton-matosov, this is live now. Please let me know if anything is wrong with the live version after our changes (it seems to be working fine for me on Windows 😄)

**Comment by anton-matosov** [comment]
Installed from vscode marketplace, all looks good!

**Pull request merged**
